use std::env;
use std::fs;
use std::path::{Path, PathBuf};

use walkdir::WalkDir;

const DOCS_ROOT: &str = "src/content/docs";

fn main() {
    let manifest_dir = env::var_os("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR not set");
    let manifest_dir = PathBuf::from(manifest_dir);
    let docs_root = manifest_dir.join(DOCS_ROOT);

    println!("cargo:rerun-if-changed={}", docs_root.display());

    let mut entries = Vec::new();
    if docs_root.is_dir() {
        for entry in WalkDir::new(&docs_root) {
            let entry = entry.expect("walkdir error in src/content/docs/");
            let path = entry.path();
            if !path.is_file() {
                continue;
            }
            let ext = match path.extension().and_then(|e| e.to_str()) {
                Some(e) => e,
                None => continue,
            };
            if ext != "md" && ext != "mdx" {
                continue;
            }
            println!("cargo:rerun-if-changed={}", path.display());
            entries.push(path.to_path_buf());
        }
    }

    entries.sort();

    let mut out = String::from("// generated by build.rs\n");
    for path in &entries {
        let rel = path
            .strip_prefix(&docs_root)
            .expect("path under docs_root");
        let module_name = sanitize_module_name(rel);
        // Use absolute path in include_str! so it works regardless of cwd.
        let include_path = path.to_string_lossy().replace('\\', "/");
        out.push_str(&format!(
            "#[doc = include_str!(\"{}\")]\npub mod {} {{}}\n",
            include_path, module_name
        ));
    }

    let out_dir = env::var_os("OUT_DIR").expect("OUT_DIR not set");
    let out_path = PathBuf::from(out_dir).join("doctests.rs");
    fs::write(&out_path, out).expect("write doctests.rs");
}

fn sanitize_module_name(rel: &Path) -> String {
    let mut s = String::from("doc");
    for component in rel.with_extension("").components() {
        if let std::path::Component::Normal(part) = component {
            s.push('_');
            for ch in part.to_string_lossy().chars() {
                if ch.is_ascii_alphanumeric() {
                    s.push(ch.to_ascii_lowercase());
                } else {
                    s.push('_');
                }
            }
        }
    }
    s
}
