[package]
name = "website"
version = "0.0.0"
edition = "2021"
publish = false
description = "Doctest harness for the Neon docs site (https://neon-rs.dev)."

[lib]
path = "src/lib.rs"

[dependencies]
neon = { path = "../crates/neon", default-features = false, features = [
    "napi-experimental",
    "external-buffers",
    "serde",
    "tokio",
] }
either = "1"
blake3 = "1"
serde_json = "1"
sqlx = { version = "0.8", default-features = false, features = [
    "runtime-tokio",
    "sqlite",
] }
tokio = { version = "1", features = ["rt-multi-thread"] }

[build-dependencies]
walkdir = "2"
