const assert = require("assert");

const addon = require("..");

describe("TypeScript declaration generation", () => {
  let declarations;

  before(() => {
    declarations = addon[Symbol.for("neon:types")];
  });

  it("generates valid declaration output", () => {
    assert.ok(typeof declarations === "string");
    assert.ok(declarations.length > 0);
    assert.ok(
      declarations.startsWith("// Auto-generated by Neon. Do not edit.")
    );
  });

  it("declares ts_add with correct signature", () => {
    assert.ok(
      declarations.includes(
        "export declare function tsAdd(a: number, b: number): number;"
      ),
      `Expected tsAdd declaration, got:\n${declarations}`
    );
  });

  it("declares ts_greet with string types", () => {
    assert.ok(
      declarations.includes(
        "export declare function tsGreet(name: string): string;"
      ),
      `Expected tsGreet declaration, got:\n${declarations}`
    );
  });

  it("declares ts_is_even with boolean return", () => {
    assert.ok(
      declarations.includes(
        "export declare function tsIsEven(n: number): boolean;"
      ),
      `Expected tsIsEven declaration, got:\n${declarations}`
    );
  });

  it("declares ts_maybe_number with optional return", () => {
    assert.ok(
      declarations.includes(
        "export declare function tsMaybeNumber(flag: boolean): number | undefined | null;"
      ),
      `Expected tsMaybeNumber declaration, got:\n${declarations}`
    );
  });

  it("declares ts_async_add as returning Promise", () => {
    assert.ok(
      declarations.includes(
        "export declare function tsAsyncAdd(a: number, b: number): Promise<number>;"
      ),
      `Expected tsAsyncAdd declaration, got:\n${declarations}`
    );
  });

  it("renders async unit return as Promise<void>, not Promise<undefined>", () => {
    assert.ok(
      declarations.includes(
        "export declare function tsAsyncNoop(): Promise<void>;"
      ),
      `Expected Promise<void>, got:\n${declarations}`
    );
    assert.ok(
      !declarations.includes("Promise<undefined>"),
      `Expected no Promise<undefined> anywhere, got:\n${declarations}`
    );
  });

  it("uses renamed export name", () => {
    assert.ok(
      declarations.includes(
        "export declare function tsRenamedFunc(x: number): number;"
      ),
      `Expected tsRenamedFunc declaration, got:\n${declarations}`
    );
  });

  it("declares ts_create_db with opaque return type", () => {
    assert.ok(
      declarations.includes(
        "export declare function tsCreateDb(): BoxedDatabase;"
      ),
      `Expected tsCreateDb declaration, got:\n${declarations}`
    );
  });

  it("declares ts_query_db with opaque parameter", () => {
    assert.ok(
      declarations.includes(
        "export declare function tsQueryDb(_db: BoxedDatabase, _query: string): string;"
      ),
      `Expected tsQueryDb declaration, got:\n${declarations}`
    );
  });

  it("declares ts_no_args_or_return as void", () => {
    assert.ok(
      declarations.includes(
        "export declare function tsNoArgsOrReturn(): void;"
      ),
      `Expected tsNoArgsOrReturn declaration, got:\n${declarations}`
    );
  });

  it("emits branded interface for opaque types", () => {
    assert.ok(
      declarations.includes("declare const __neon_tag: unique symbol;"),
      `Expected __neon_tag symbol, got:\n${declarations}`
    );
    assert.ok(
      declarations.includes("interface BoxedDatabase"),
      `Expected BoxedDatabase interface, got:\n${declarations}`
    );
  });

  // Stage 2: Derived types

  it("derives interface for struct with rename_all", () => {
    assert.ok(
      declarations.includes("interface SearchResult {"),
      `Expected SearchResult interface, got:\n${declarations}`
    );
    assert.ok(
      declarations.includes("  docId: number;"),
      `Expected camelCase field docId, got:\n${declarations}`
    );
    assert.ok(
      declarations.includes("  score: number;"),
      `Expected score field, got:\n${declarations}`
    );
    assert.ok(
      !declarations.includes("  internal:"),
      `Expected internal to be skipped, got:\n${declarations}`
    );
    assert.ok(
      declarations.includes("  highlights?: string[];"),
      `Expected optional highlights field, got:\n${declarations}`
    );
  });

  it("derives discriminated union for internally tagged enum", () => {
    assert.ok(
      declarations.includes("type Shape ="),
      `Expected Shape type, got:\n${declarations}`
    );
    assert.ok(
      declarations.includes('kind: "circle"'),
      `Expected circle variant, got:\n${declarations}`
    );
    assert.ok(
      declarations.includes('kind: "rectangle"'),
      `Expected rectangle variant, got:\n${declarations}`
    );
    assert.ok(
      declarations.includes('kind: "dot"'),
      `Expected renamed dot variant, got:\n${declarations}`
    );
    assert.ok(
      declarations.includes("radius: number"),
      `Expected radius field, got:\n${declarations}`
    );
  });

  it("derives transparent struct as inner type", () => {
    // Wrapper(String) with #[serde(transparent)] should not produce its own interface;
    // functions using Json<Wrapper> should show "string" directly
  });

  it("supports #[neon(ts_type)] field override", () => {
    assert.ok(
      declarations.includes("interface Config {"),
      `Expected Config interface, got:\n${declarations}`
    );
    assert.ok(
      declarations.includes("  metadata: Record<string, unknown>;"),
      `Expected ts_type override for metadata, got:\n${declarations}`
    );
  });

  it("uses derived types in function signatures via Json<T>", () => {
    assert.ok(
      declarations.includes(
        "export declare function tsSearch(query: string): SearchResult;"
      ),
      `Expected tsSearch declaration, got:\n${declarations}`
    );
    assert.ok(
      declarations.includes(
        "export declare function tsCreateShape(kind: string): Shape;"
      ),
      `Expected tsCreateShape declaration, got:\n${declarations}`
    );
    assert.ok(
      declarations.includes("export declare function tsGetConfig(): Config;"),
      `Expected tsGetConfig declaration, got:\n${declarations}`
    );
  });

  // Stage 4: Extended enum representations

  it("derives externally tagged enum (serde default)", () => {
    assert.ok(
      declarations.includes("type ExternalMsg ="),
      `Expected ExternalMsg type, got:\n${declarations}`
    );
    // Unit variant → string literal
    assert.ok(
      declarations.includes('"Quit"'),
      `Expected "Quit" string literal, got:\n${declarations}`
    );
    // Newtype variant → { Echo: string }
    assert.ok(
      declarations.includes("{ Echo: string }"),
      `Expected Echo newtype variant, got:\n${declarations}`
    );
    // Struct variant → { Move: { x: number; y: number; } }
    assert.ok(
      declarations.includes("{ Move: {"),
      `Expected Move struct variant, got:\n${declarations}`
    );
    assert.ok(
      declarations.includes("x: number;"),
      `Expected x field in Move, got:\n${declarations}`
    );
  });

  it("derives adjacently tagged enum", () => {
    assert.ok(
      declarations.includes("type ApiResponse ="),
      `Expected ApiResponse type, got:\n${declarations}`
    );
    // Newtype → { type: "Success", data: string }
    assert.ok(
      declarations.includes('type: "Success"'),
      `Expected Success variant, got:\n${declarations}`
    );
    assert.ok(
      declarations.includes("data: string"),
      `Expected data field for Success, got:\n${declarations}`
    );
    // Struct → { type: "Error", data: { code: number; ... } }
    assert.ok(
      declarations.includes('type: "Error"'),
      `Expected Error variant, got:\n${declarations}`
    );
    // Unit → { type: "Loading" } (no data field)
    assert.ok(
      declarations.includes('type: "Loading"'),
      `Expected Loading variant, got:\n${declarations}`
    );
  });

  it("derives untagged enum as plain union", () => {
    assert.ok(
      declarations.includes("type StringOrNumber ="),
      `Expected StringOrNumber type, got:\n${declarations}`
    );
    // Should be a union of inner types directly
    assert.ok(
      declarations.includes("string | number"),
      `Expected string | number union, got:\n${declarations}`
    );
  });

  it("uses extended enum types in function signatures", () => {
    assert.ok(
      declarations.includes(
        "export declare function tsSendMessage(kind: string): ExternalMsg;"
      ),
      `Expected tsSendMessage declaration, got:\n${declarations}`
    );
    assert.ok(
      declarations.includes(
        "export declare function tsApiResponse(ok: boolean): ApiResponse;"
      ),
      `Expected tsApiResponse declaration, got:\n${declarations}`
    );
    assert.ok(
      declarations.includes(
        "export declare function tsParseValue(input: string): StringOrNumber;"
      ),
      `Expected tsParseValue declaration, got:\n${declarations}`
    );
  });

  it("maps serde_json::Value to any", () => {
    assert.ok(
      declarations.includes("export declare function tsGetAnyValue(): any;"),
      `Expected tsGetAnyValue returning any, got:\n${declarations}`
    );
  });

  // Stage 4b: Flatten and generics

  it("generates intersection type for #[serde(flatten)]", () => {
    assert.ok(
      declarations.includes("interface UserList {"),
      `Expected UserList interface, got:\n${declarations}`
    );
    assert.ok(
      declarations.includes("} & Pagination"),
      `Expected intersection with Pagination, got:\n${declarations}`
    );
    assert.ok(
      declarations.includes("interface Pagination {"),
      `Expected Pagination interface, got:\n${declarations}`
    );
    assert.ok(
      declarations.includes(
        "export declare function tsGetUserList(): UserList;"
      ),
      `Expected tsGetUserList declaration, got:\n${declarations}`
    );
  });

  it("generates generic interface with type parameters", () => {
    assert.ok(
      declarations.includes("interface Envelope<T> {"),
      `Expected generic Envelope<T> interface, got:\n${declarations}`
    );
    assert.ok(
      declarations.includes("  data: T;"),
      `Expected generic field data: T, got:\n${declarations}`
    );
    assert.ok(
      declarations.includes("  timestamp: number;"),
      `Expected concrete field timestamp: number, got:\n${declarations}`
    );
  });

  it("uses concrete generic types in function signatures", () => {
    assert.ok(
      declarations.includes(
        "export declare function tsGetStringEnvelope(): Envelope<string>;"
      ),
      `Expected Envelope<string> return, got:\n${declarations}`
    );
    assert.ok(
      declarations.includes(
        "export declare function tsGetNumberEnvelope(): Envelope<number>;"
      ),
      `Expected Envelope<number> return, got:\n${declarations}`
    );
  });

  // Stage 3: Class exports

  it("generates declare class with constructor and methods", () => {
    assert.ok(
      declarations.includes("export declare class Point {"),
      `Expected Point class, got:\n${declarations}`
    );
    assert.ok(
      declarations.includes("  constructor(x: number, y: number);"),
      `Expected Point constructor, got:\n${declarations}`
    );
    assert.ok(
      declarations.includes("  x(): number;"),
      `Expected x() method, got:\n${declarations}`
    );
    assert.ok(
      declarations.includes("  y(): number;"),
      `Expected y() method, got:\n${declarations}`
    );
  });

  it("resolves Self to class name in method params and returns", () => {
    assert.ok(
      declarations.includes("  distance(other: Point): number;"),
      `Expected distance(other: Point), got:\n${declarations}`
    );
    assert.ok(
      declarations.includes("  midpoint(other: Point): Point;"),
      `Expected midpoint returning Point, got:\n${declarations}`
    );
  });

  it("generates static readonly for const properties", () => {
    assert.ok(
      declarations.includes("  static readonly ORIGIN_X: number;"),
      `Expected ORIGIN_X static, got:\n${declarations}`
    );
    assert.ok(
      declarations.includes("  static readonly IS_2D: boolean;"),
      `Expected IS_2D static, got:\n${declarations}`
    );
  });

  it("uses custom names for const properties", () => {
    assert.ok(
      declarations.includes("  static readonly maxCoordinate: number;"),
      `Expected renamed maxCoordinate, got:\n${declarations}`
    );
  });

  it("generates Promise return for async/task methods", () => {
    assert.ok(
      declarations.includes("  asyncMethod(suffix: string): Promise<string>;"),
      `Expected async method with Promise, got:\n${declarations}`
    );
    assert.ok(
      declarations.includes("  heavyComputation(): Promise<number>;"),
      `Expected task method with Promise, got:\n${declarations}`
    );
  });

  it("hides context and channel params from methods", () => {
    // taskWithChannel(self, _ch: Channel, multiplier: i32) should only show multiplier
    assert.ok(
      declarations.includes(
        "  taskWithChannel(multiplier: number): Promise<string>;"
      ),
      `Expected channel param hidden, got:\n${declarations}`
    );
  });

  it("generates class with no constructor for Default types", () => {
    assert.ok(
      declarations.includes("export declare class StringBuffer {"),
      `Expected StringBuffer class, got:\n${declarations}`
    );
    // StringBuffer uses Default, no constructor
    assert.ok(
      !declarations.includes(
        "export declare class StringBuffer {\n  constructor"
      ),
      `Expected no constructor for StringBuffer, got:\n${declarations}`
    );
  });

  it("uses class types in standalone function signatures", () => {
    assert.ok(
      declarations.includes(
        "export declare function createPointFromRust(x: number, y: number): Point;"
      ),
      `Expected createPointFromRust returning Point, got:\n${declarations}`
    );
  });

  it("uses renamed method names via #[neon(name)]", () => {
    assert.ok(
      declarations.includes("  includes(s: string): boolean;"),
      `Expected renamed includes method, got:\n${declarations}`
    );
    assert.ok(
      declarations.includes("  trimStart(): string;"),
      `Expected renamed trimStart method, got:\n${declarations}`
    );
  });

  // --- New attributes ---

  it("hides ts_skip-marked functions", () => {
    assert.ok(
      !declarations.includes("tsSkippedFunction"),
      `Expected tsSkippedFunction to be skipped, got:\n${declarations}`
    );
  });

  it("hides ts_skip-marked classes", () => {
    assert.ok(
      !declarations.includes("declare class Hidden"),
      `Expected Hidden class to be skipped, got:\n${declarations}`
    );
  });

  it("hides ts_skip-marked methods", () => {
    assert.ok(
      !declarations.includes("tsInternalMethod"),
      `Expected tsInternalMethod to be skipped, got:\n${declarations}`
    );
  });

  it("applies ts_returns override on functions", () => {
    assert.ok(
      declarations.includes("tsReturnsOverride(): bigint"),
      `Expected tsReturnsOverride to return bigint, got:\n${declarations}`
    );
  });

  it("maps Handle<JsBigInt> to bigint", () => {
    assert.ok(
      declarations.includes("tsBigintReturn(): bigint"),
      `Expected JsBigInt to map to bigint, got:\n${declarations}`
    );
  });

  it("maps Handle<JsString> to string", () => {
    assert.ok(
      declarations.includes("tsHandleStringReturn(): string"),
      `Expected JsString handle to map to string, got:\n${declarations}`
    );
  });

  // --- Built-in TypeScript impls for collection/composed types ---

  it("emits Record<string, V> for HashMap<K, V>", () => {
    assert.ok(
      declarations.includes("tsGetScores(): Record<string, number>"),
      `Expected HashMap to map to Record, got:\n${declarations}`
    );
  });

  it("uses Record<string, V> even for non-string map keys (JSON stringifies keys)", () => {
    assert.ok(
      declarations.includes("tsGetCounts(): Record<string, number>"),
      `Expected Record<string, number> for HashMap<u32, f64>, got:\n${declarations}`
    );
    assert.ok(
      !declarations.includes("Record<number,"),
      `Expected no Record<number, ...>, got:\n${declarations}`
    );
  });

  it("emits [A, B] for 2-tuple and [A, B, C] for 3-tuple", () => {
    assert.ok(
      declarations.includes("tsGetPair(): [number, string]"),
      `Expected 2-tuple syntax, got:\n${declarations}`
    );
    assert.ok(
      declarations.includes("tsGetTriple(): [number, string, boolean]"),
      `Expected 3-tuple syntax, got:\n${declarations}`
    );
  });

  it("emits Record<K, V[]> for HashMap<K, Vec<V>> (nested generic)", () => {
    assert.ok(
      declarations.includes("tsGetNested(): Record<string, number[]>"),
      `Expected nested generic, got:\n${declarations}`
    );
  });

  it("collects ts_decl interface from a manual TypeScript impl", () => {
    // GeoPoint has a manual `impl TypeScript` whose `ts_decl()` returns a
    // full interface body. The generator should pick it up via ts_collect.
    assert.ok(
      declarations.includes("export interface GeoPoint {"),
      `Expected GeoPoint interface, got:\n${declarations}`
    );
    assert.ok(
      declarations.includes("  lat: number;"),
      `Expected lat field, got:\n${declarations}`
    );
    assert.ok(
      declarations.includes("tsGetPoint(): GeoPoint"),
      `Expected GeoPoint reference, got:\n${declarations}`
    );
  });

  it("ts_strict on a function compiles (impls present, no fallback)", () => {
    assert.ok(
      declarations.includes(
        "tsStrictFunction(name: string, count: number): number"
      ),
      `Expected tsStrictFunction signature, got:\n${declarations}`
    );
  });

  it("ts_no_constructor omits the constructor", () => {
    const match = declarations.match(
      /export declare class NoCtor \{([\s\S]*?)\}/
    );
    assert.ok(match, "Expected NoCtor class declaration");
    assert.ok(
      !match[1].includes("constructor("),
      `Expected no constructor, got:\n${match[1]}`
    );
    assert.ok(
      match[1].includes("ping("),
      `Expected ping method preserved, got:\n${match[1]}`
    );
  });

  it("ts_skip on fn new omits the constructor", () => {
    const match = declarations.match(
      /export declare class CtorSkipped \{([\s\S]*?)\}/
    );
    assert.ok(match, "Expected CtorSkipped class declaration");
    assert.ok(
      !match[1].includes("constructor("),
      `Expected no constructor, got:\n${match[1]}`
    );
    assert.ok(
      match[1].includes("ping("),
      `Expected ping method preserved, got:\n${match[1]}`
    );
  });

  describe("module scoping", () => {
    it("wraps output in declare module when module option is set", () => {
      const wrapped = addon.tsGenerateModuleWrapped("./load.cjs");
      assert.ok(
        wrapped.includes('declare module "./load.cjs" {'),
        `Expected module wrapping, got:\n${wrapped}`
      );
      assert.ok(
        wrapped.trimEnd().endsWith("}"),
        `Expected closing brace, got end:\n${wrapped.slice(-100)}`
      );
      // Body should be indented
      assert.ok(
        /\n  export declare function /.test(wrapped),
        `Expected indented body, got:\n${wrapped.slice(0, 500)}`
      );
    });

    it("keeps the file header above the module wrapper", () => {
      const wrapped = addon.tsGenerateModuleWrapped("foo");
      assert.ok(
        wrapped.startsWith("// Auto-generated by Neon. Do not edit.\n"),
        `Expected header at top, got:\n${wrapped.slice(0, 100)}`
      );
    });
  });

  it("applies ts_returns override on methods", () => {
    assert.ok(
      declarations.includes("tsMethodReturns(): bigint"),
      `Expected tsMethodReturns to return bigint, got:\n${declarations}`
    );
  });

  it("applies per-param ts_type override", () => {
    assert.ok(
      declarations.includes("tsParamOverride(xs: ReadonlyArray<number>)"),
      `Expected ts_type override on param, got:\n${declarations}`
    );
  });

  it("applies ts_name to classes", () => {
    assert.ok(
      declarations.includes("declare class PublicName"),
      `Expected renamed class PublicName, got:\n${declarations}`
    );
    assert.ok(
      !/declare class Renamed\s/.test(declarations),
      `Expected original Rust name not in output, got:\n${declarations}`
    );
  });

  it("applies ts_name to methods", () => {
    assert.ok(
      declarations.includes("publicName(): string"),
      `Expected renamed method publicName, got:\n${declarations}`
    );
  });

  it('auto-attaches declarations under Symbol.for("neon:types")', () => {
    const fromSymbol = addon[Symbol.for("neon:types")];
    assert.strictEqual(typeof fromSymbol, "string");
    assert.ok(fromSymbol.length > 0);
  });

  describe("structured AST output", () => {
    let ast;

    before(() => {
      ast = JSON.parse(addon[Symbol.for("neon:types-ast")]);
    });

    it('auto-attaches AST under Symbol.for("neon:types-ast")', () => {
      assert.ok(Array.isArray(ast));
      assert.ok(ast.length > 0);
    });

    it("emits TSDeclareFunction for exported functions", () => {
      const fn = ast.find(
        (d) => d.type === "TSDeclareFunction" && d.id.name === "tsAdd"
      );
      assert.ok(fn, "tsAdd not found");
      assert.strictEqual(fn.params.length, 2);
      assert.strictEqual(fn.params[0].name, "a");
      assert.strictEqual(
        fn.params[0].typeAnnotation.typeAnnotation.type,
        "TSNumberKeyword"
      );
      assert.strictEqual(fn.returnType.typeAnnotation.type, "TSNumberKeyword");
    });

    it("emits ClassDeclaration for exported classes", () => {
      const cls = ast.find(
        (d) => d.type === "ClassDeclaration" && d.id.name === "Point"
      );
      assert.ok(cls, "Point class not found");
      assert.strictEqual(cls.declare, true);
      assert.ok(Array.isArray(cls.body.body));
      const ctor = cls.body.body.find(
        (m) => m.type === "MethodDefinition" && m.kind === "constructor"
      );
      assert.ok(ctor, "constructor not found");
      assert.strictEqual(ctor.value.params.length, 2);
    });

    it('emits TSAnyKeyword for ts_returns="any" overrides', () => {
      // Find a method with bigint return (ts_returns override)
      const cls = ast.find(
        (d) => d.type === "ClassDeclaration" && d.id.name === "PublicName"
      );
      const method = cls.body.body.find(
        (m) => m.type === "MethodDefinition" && m.key.name === "tsMethodReturns"
      );
      assert.strictEqual(
        method.value.returnType.typeAnnotation.type,
        "TSBigIntKeyword"
      );
    });

    it("emits TSArrayType for Vec<T> via parser", () => {
      const fn = ast.find(
        (d) => d.type === "TSDeclareFunction" && d.id.name === "tsParamOverride"
      );
      // ts_type override: "ReadonlyArray<number>" -> reference with type args
      assert.strictEqual(
        fn.params[0].typeAnnotation.typeAnnotation.type,
        "TSTypeReference"
      );
      assert.strictEqual(
        fn.params[0].typeAnnotation.typeAnnotation.typeName.name,
        "ReadonlyArray"
      );
    });

    it("wraps async returns in Promise reference", () => {
      const fn = ast.find(
        (d) => d.type === "TSDeclareFunction" && d.id.name === "tsAsyncAdd"
      );
      assert.strictEqual(fn.returnType.typeAnnotation.type, "TSTypeReference");
      assert.strictEqual(fn.returnType.typeAnnotation.typeName.name, "Promise");
    });

    it("emits Raw nodes for collected interface/type-alias decls (transitional)", () => {
      const raw = ast.find((d) => d.type === "Raw");
      // Currently TSInterfaceDeclaration / TSTypeAliasDeclaration come through
      // as Raw; future change will promote them.
      assert.ok(raw, "expected at least one Raw decl");
      assert.strictEqual(typeof raw.value, "string");
    });
  });

  it("emits export keyword on type aliases and interfaces", () => {
    // Find any non-class/non-function declaration line and verify export prefix.
    // Spot-check with known types:
    assert.ok(
      declarations.includes("export interface SearchResult"),
      `Expected export keyword on interface, got:\n${declarations}`
    );
    assert.ok(
      declarations.includes("export type Shape"),
      `Expected export keyword on type alias, got:\n${declarations}`
    );
  });
});
