const assert = require("assert");

const addon = require("..");

describe("TypeScript declaration generation", () => {
  let declarations;

  before(() => {
    declarations = addon[Symbol.for("neon:types")];
  });

  it("generates valid declaration output", () => {
    assert.ok(typeof declarations === "string");
    assert.ok(declarations.length > 0);
    assert.ok(
      declarations.startsWith("// Auto-generated by Neon. Do not edit.")
    );
  });

  it("declares ts_add with correct signature", () => {
    assert.ok(
      declarations.includes(
        "export declare function tsAdd(a: number, b: number): number;"
      ),
      `Expected tsAdd declaration, got:\n${declarations}`
    );
  });

  it("declares ts_greet with string types", () => {
    assert.ok(
      declarations.includes(
        "export declare function tsGreet(name: string): string;"
      ),
      `Expected tsGreet declaration, got:\n${declarations}`
    );
  });

  it("declares ts_is_even with boolean return", () => {
    assert.ok(
      declarations.includes(
        "export declare function tsIsEven(n: number): boolean;"
      ),
      `Expected tsIsEven declaration, got:\n${declarations}`
    );
  });

  it("declares ts_maybe_number with optional return", () => {
    // Option<T> renders as `T | null` (Neon's neon-typescript mapping).
    assert.ok(
      declarations.includes(
        "export declare function tsMaybeNumber(flag: boolean): number | null;"
      ),
      `Expected tsMaybeNumber declaration, got:\n${declarations}`
    );
  });

  it("declares ts_async_add as returning Promise", () => {
    assert.ok(
      declarations.includes(
        "export declare function tsAsyncAdd(a: number, b: number): Promise<number>;"
      ),
      `Expected tsAsyncAdd declaration, got:\n${declarations}`
    );
  });

  it("renders async unit return as Promise<void>, not Promise<undefined>", () => {
    assert.ok(
      declarations.includes(
        "export declare function tsAsyncNoop(): Promise<void>;"
      ),
      `Expected Promise<void>, got:\n${declarations}`
    );
    assert.ok(
      !declarations.includes("Promise<undefined>"),
      `Expected no Promise<undefined> anywhere, got:\n${declarations}`
    );
  });

  it("uses renamed export name", () => {
    assert.ok(
      declarations.includes(
        "export declare function tsRenamedFunc(x: number): number;"
      ),
      `Expected tsRenamedFunc declaration, got:\n${declarations}`
    );
  });

  it("declares ts_create_db with opaque return type", () => {
    assert.ok(
      declarations.includes(
        "export declare function tsCreateDb(): BoxedDatabase;"
      ),
      `Expected tsCreateDb declaration, got:\n${declarations}`
    );
  });

  it("declares ts_query_db with opaque parameter", () => {
    assert.ok(
      declarations.includes(
        "export declare function tsQueryDb(_db: BoxedDatabase, _query: string): string;"
      ),
      `Expected tsQueryDb declaration, got:\n${declarations}`
    );
  });

  it("declares ts_no_args_or_return as void", () => {
    assert.ok(
      declarations.includes(
        "export declare function tsNoArgsOrReturn(): void;"
      ),
      `Expected tsNoArgsOrReturn declaration, got:\n${declarations}`
    );
  });

  it("emits branded interface for opaque types", () => {
    assert.ok(
      declarations.includes("declare const __neon_tag: unique symbol;"),
      `Expected __neon_tag symbol, got:\n${declarations}`
    );
    assert.ok(
      declarations.includes("interface BoxedDatabase"),
      `Expected BoxedDatabase interface, got:\n${declarations}`
    );
  });

  // Derived types (bridged from ts-rs via neon-ts-rs).
  //
  // ts-rs owns the exact serde-to-TypeScript rendering (tested in the ts-rs and
  // neon-ts-rs crates), so these assertions only prove the bridge works
  // end-to-end for a representative type. Note ts-rs emits `type X = { ... }`
  // (comma-separated fields), uses `Array<T>` rather than `T[]`, and quotes
  // discriminant keys.

  it("derives a type alias for a struct with rename_all", () => {
    assert.ok(
      declarations.includes("type SearchResult ="),
      `Expected SearchResult type, got:\n${declarations}`
    );
    // rename_all = "camelCase" is honored via serde-compat.
    assert.ok(
      declarations.includes("docId: number"),
      `Expected camelCase field docId, got:\n${declarations}`
    );
    // #[serde(skip)] field is omitted.
    assert.ok(
      !declarations.includes("internal:"),
      `Expected internal to be skipped, got:\n${declarations}`
    );
    // Vec<String> renders as Array<string>.
    assert.ok(
      declarations.includes("highlights: Array<string>"),
      `Expected highlights: Array<string>, got:\n${declarations}`
    );
  });

  it("derives a discriminated union for an internally tagged enum", () => {
    assert.ok(
      declarations.includes("type Shape ="),
      `Expected Shape type, got:\n${declarations}`
    );
    // ts-rs quotes the discriminant key.
    assert.ok(
      declarations.includes('"kind": "circle"'),
      `Expected circle variant, got:\n${declarations}`
    );
    assert.ok(
      declarations.includes('"kind": "dot"'),
      `Expected renamed dot variant, got:\n${declarations}`
    );
    assert.ok(
      declarations.includes("radius: number"),
      `Expected radius field, got:\n${declarations}`
    );
  });

  it("supports #[ts(type = ...)] field override", () => {
    assert.ok(
      declarations.includes("type Config ="),
      `Expected Config type, got:\n${declarations}`
    );
    assert.ok(
      declarations.includes("metadata: Record<string, unknown>"),
      `Expected ts(type) override for metadata, got:\n${declarations}`
    );
  });

  it("uses derived types in function signatures via Json<T>", () => {
    assert.ok(
      declarations.includes(
        "export declare function tsSearch(query: string): SearchResult;"
      ),
      `Expected tsSearch declaration, got:\n${declarations}`
    );
    assert.ok(
      declarations.includes(
        "export declare function tsCreateShape(kind: string): Shape;"
      ),
      `Expected tsCreateShape declaration, got:\n${declarations}`
    );
    assert.ok(
      declarations.includes("export declare function tsGetConfig(): Config;"),
      `Expected tsGetConfig declaration, got:\n${declarations}`
    );
  });

  // Enum representations. The exhaustive per-tagging-mode assertions now live in
  // the ts-rs / neon-ts-rs crates; here we keep one representative union plus a
  // check that enums flow through function signatures.

  it("derives untagged enum as plain union", () => {
    assert.ok(
      declarations.includes("type StringOrNumber ="),
      `Expected StringOrNumber type, got:\n${declarations}`
    );
    // Should be a union of inner types directly
    assert.ok(
      declarations.includes("string | number"),
      `Expected string | number union, got:\n${declarations}`
    );
  });

  it("uses extended enum types in function signatures", () => {
    assert.ok(
      declarations.includes(
        "export declare function tsSendMessage(kind: string): ExternalMsg;"
      ),
      `Expected tsSendMessage declaration, got:\n${declarations}`
    );
    assert.ok(
      declarations.includes(
        "export declare function tsApiResponse(ok: boolean): ApiResponse;"
      ),
      `Expected tsApiResponse declaration, got:\n${declarations}`
    );
    assert.ok(
      declarations.includes(
        "export declare function tsParseValue(input: string): StringOrNumber;"
      ),
      `Expected tsParseValue declaration, got:\n${declarations}`
    );
  });

  it("maps serde_json::Value to any", () => {
    assert.ok(
      declarations.includes("export declare function tsGetAnyValue(): any;"),
      `Expected tsGetAnyValue returning any, got:\n${declarations}`
    );
  });

  // Flatten and generics.

  it("inlines #[serde(flatten)] fields", () => {
    // ts-rs inlines flattened fields into the type (rather than emitting a
    // TypeScript intersection with a separate Pagination type).
    assert.ok(
      declarations.includes("type UserList ="),
      `Expected UserList type, got:\n${declarations}`
    );
    assert.ok(
      declarations.includes("users: Array<string>"),
      `Expected users field, got:\n${declarations}`
    );
    assert.ok(
      declarations.includes("page: number"),
      `Expected flattened page field, got:\n${declarations}`
    );
    assert.ok(
      declarations.includes(
        "export declare function tsGetUserList(): UserList;"
      ),
      `Expected tsGetUserList declaration, got:\n${declarations}`
    );
  });

  it("generates a generic type with type parameters", () => {
    assert.ok(
      declarations.includes("type Envelope<T> ="),
      `Expected generic Envelope<T> type, got:\n${declarations}`
    );
    assert.ok(
      declarations.includes("data: T"),
      `Expected generic field data: T, got:\n${declarations}`
    );
    assert.ok(
      declarations.includes("timestamp: number"),
      `Expected concrete field timestamp: number, got:\n${declarations}`
    );
  });

  it("uses concrete generic types in function signatures", () => {
    assert.ok(
      declarations.includes(
        "export declare function tsGetStringEnvelope(): Envelope<string>;"
      ),
      `Expected Envelope<string> return, got:\n${declarations}`
    );
    assert.ok(
      declarations.includes(
        "export declare function tsGetNumberEnvelope(): Envelope<number>;"
      ),
      `Expected Envelope<number> return, got:\n${declarations}`
    );
  });

  // Stage 3: Class exports

  it("generates declare class with constructor and methods", () => {
    assert.ok(
      declarations.includes("export declare class Point {"),
      `Expected Point class, got:\n${declarations}`
    );
    assert.ok(
      declarations.includes("  constructor(x: number, y: number);"),
      `Expected Point constructor, got:\n${declarations}`
    );
    assert.ok(
      declarations.includes("  x(): number;"),
      `Expected x() method, got:\n${declarations}`
    );
    assert.ok(
      declarations.includes("  y(): number;"),
      `Expected y() method, got:\n${declarations}`
    );
  });

  it("resolves Self to class name in method params and returns", () => {
    assert.ok(
      declarations.includes("  distance(other: Point): number;"),
      `Expected distance(other: Point), got:\n${declarations}`
    );
    assert.ok(
      declarations.includes("  midpoint(other: Point): Point;"),
      `Expected midpoint returning Point, got:\n${declarations}`
    );
  });

  it("generates static readonly for const properties", () => {
    assert.ok(
      declarations.includes("  static readonly ORIGIN_X: number;"),
      `Expected ORIGIN_X static, got:\n${declarations}`
    );
    assert.ok(
      declarations.includes("  static readonly IS_2D: boolean;"),
      `Expected IS_2D static, got:\n${declarations}`
    );
  });

  it("uses custom names for const properties", () => {
    assert.ok(
      declarations.includes("  static readonly maxCoordinate: number;"),
      `Expected renamed maxCoordinate, got:\n${declarations}`
    );
  });

  it("generates Promise return for async/task methods", () => {
    assert.ok(
      declarations.includes("  asyncMethod(suffix: string): Promise<string>;"),
      `Expected async method with Promise, got:\n${declarations}`
    );
    assert.ok(
      declarations.includes("  heavyComputation(): Promise<number>;"),
      `Expected task method with Promise, got:\n${declarations}`
    );
  });

  it("hides context and channel params from methods", () => {
    // taskWithChannel(self, _ch: Channel, multiplier: i32) should only show multiplier
    assert.ok(
      declarations.includes(
        "  taskWithChannel(multiplier: number): Promise<string>;"
      ),
      `Expected channel param hidden, got:\n${declarations}`
    );
  });

  it("generates class with no constructor for Default types", () => {
    assert.ok(
      declarations.includes("export declare class StringBuffer {"),
      `Expected StringBuffer class, got:\n${declarations}`
    );
    // StringBuffer uses Default, no constructor
    assert.ok(
      !declarations.includes(
        "export declare class StringBuffer {\n  constructor"
      ),
      `Expected no constructor for StringBuffer, got:\n${declarations}`
    );
  });

  it("uses class types in standalone function signatures", () => {
    assert.ok(
      declarations.includes(
        "export declare function createPointFromRust(x: number, y: number): Point;"
      ),
      `Expected createPointFromRust returning Point, got:\n${declarations}`
    );
  });

  it("uses renamed method names via #[neon(name)]", () => {
    assert.ok(
      declarations.includes("  includes(s: string): boolean;"),
      `Expected renamed includes method, got:\n${declarations}`
    );
    assert.ok(
      declarations.includes("  trimStart(): string;"),
      `Expected renamed trimStart method, got:\n${declarations}`
    );
  });

  // --- New attributes ---

  it("hides ts_skip-marked functions", () => {
    assert.ok(
      !declarations.includes("tsSkippedFunction"),
      `Expected tsSkippedFunction to be skipped, got:\n${declarations}`
    );
  });

  it("hides ts_skip-marked classes", () => {
    assert.ok(
      !declarations.includes("declare class Hidden"),
      `Expected Hidden class to be skipped, got:\n${declarations}`
    );
  });

  it("hides ts_skip-marked methods", () => {
    assert.ok(
      !declarations.includes("tsInternalMethod"),
      `Expected tsInternalMethod to be skipped, got:\n${declarations}`
    );
  });

  it("applies ts_returns override on functions", () => {
    assert.ok(
      declarations.includes("tsReturnsOverride(): bigint"),
      `Expected tsReturnsOverride to return bigint, got:\n${declarations}`
    );
  });

  it("maps Handle<JsBigInt> to bigint", () => {
    assert.ok(
      declarations.includes("tsBigintReturn(): bigint"),
      `Expected JsBigInt to map to bigint, got:\n${declarations}`
    );
  });

  it("maps Handle<JsString> to string", () => {
    assert.ok(
      declarations.includes("tsHandleStringReturn(): string"),
      `Expected JsString handle to map to string, got:\n${declarations}`
    );
  });

  // --- Built-in TypeScript impls for collection/composed types ---

  it("emits Record<string, V> for HashMap<K, V>", () => {
    assert.ok(
      declarations.includes("tsGetScores(): Record<string, number>"),
      `Expected HashMap to map to Record, got:\n${declarations}`
    );
  });

  it("uses Record<string, V> even for non-string map keys (JSON stringifies keys)", () => {
    assert.ok(
      declarations.includes("tsGetCounts(): Record<string, number>"),
      `Expected Record<string, number> for HashMap<u32, f64>, got:\n${declarations}`
    );
    assert.ok(
      !declarations.includes("Record<number,"),
      `Expected no Record<number, ...>, got:\n${declarations}`
    );
  });

  it("emits [A, B] for 2-tuple and [A, B, C] for 3-tuple", () => {
    assert.ok(
      declarations.includes("tsGetPair(): [number, string]"),
      `Expected 2-tuple syntax, got:\n${declarations}`
    );
    assert.ok(
      declarations.includes("tsGetTriple(): [number, string, boolean]"),
      `Expected 3-tuple syntax, got:\n${declarations}`
    );
  });

  it("emits Record<K, V[]> for HashMap<K, Vec<V>> (nested generic)", () => {
    assert.ok(
      declarations.includes("tsGetNested(): Record<string, number[]>"),
      `Expected nested generic, got:\n${declarations}`
    );
  });

  it("collects ts_decl interface from a manual TypeScript impl", () => {
    // GeoPoint has a manual `impl TypeScript` whose `ts_decl()` returns a
    // full interface body. The generator should pick it up via ts_collect.
    assert.ok(
      declarations.includes("export interface GeoPoint {"),
      `Expected GeoPoint interface, got:\n${declarations}`
    );
    assert.ok(
      declarations.includes("  lat: number;"),
      `Expected lat field, got:\n${declarations}`
    );
    assert.ok(
      declarations.includes("tsGetPoint(): GeoPoint"),
      `Expected GeoPoint reference, got:\n${declarations}`
    );
  });

  it("resolves a foreign map at a Json boundary through ts-rs (rung 2)", () => {
    // IndexMap has no `neon_typescript::TypeScript` impl, only `ts_rs::TS`.
    // With `use neon_ts_rs::TypeScriptExt as _;` in scope, the boundary rung
    // renders it through ts-rs (a mapped type over FieldDescriptor) instead of
    // degrading to `any`.
    assert.ok(
      declarations.includes("tsIndexMap()"),
      `Expected tsIndexMap declaration, got:\n${declarations}`
    );
    assert.ok(
      declarations.includes("FieldDescriptor") &&
        /tsIndexMap\(\):[^;]*FieldDescriptor/.test(declarations),
      `Expected tsIndexMap to reference FieldDescriptor (not any), got:\n${declarations}`
    );
    assert.ok(
      !/tsIndexMap\(\): any/.test(declarations),
      `tsIndexMap must not degrade to any, got:\n${declarations}`
    );
  });

  it("keeps a type reachable only through a foreign boundary map (regression)", () => {
    // The core regression: the type referenced only via the IndexMap value must
    // not vanish from the output. Its declaration must be collected.
    assert.ok(
      /(interface|type) FieldDescriptor\b/.test(declarations),
      `Expected FieldDescriptor declaration, got:\n${declarations}`
    );
  });

  it("ts_strict on a function compiles (impls present, no fallback)", () => {
    assert.ok(
      declarations.includes(
        "tsStrictFunction(name: string, count: number): number"
      ),
      `Expected tsStrictFunction signature, got:\n${declarations}`
    );
  });

  it("ts_no_constructor omits the constructor", () => {
    const match = declarations.match(
      /export declare class NoCtor \{([\s\S]*?)\}/
    );
    assert.ok(match, "Expected NoCtor class declaration");
    assert.ok(
      !match[1].includes("constructor("),
      `Expected no constructor, got:\n${match[1]}`
    );
    assert.ok(
      match[1].includes("ping("),
      `Expected ping method preserved, got:\n${match[1]}`
    );
  });

  it("ts_skip on fn new omits the constructor", () => {
    const match = declarations.match(
      /export declare class CtorSkipped \{([\s\S]*?)\}/
    );
    assert.ok(match, "Expected CtorSkipped class declaration");
    assert.ok(
      !match[1].includes("constructor("),
      `Expected no constructor, got:\n${match[1]}`
    );
    assert.ok(
      match[1].includes("ping("),
      `Expected ping method preserved, got:\n${match[1]}`
    );
  });

  describe("module scoping", () => {
    it("wraps output in declare module when module option is set", () => {
      const wrapped = addon.tsGenerateModuleWrapped("./load.cjs");
      assert.ok(
        wrapped.includes('declare module "./load.cjs" {'),
        `Expected module wrapping, got:\n${wrapped}`
      );
      assert.ok(
        wrapped.trimEnd().endsWith("}"),
        `Expected closing brace, got end:\n${wrapped.slice(-100)}`
      );
      // Body should be indented
      assert.ok(
        /\n  export declare function /.test(wrapped),
        `Expected indented body, got:\n${wrapped.slice(0, 500)}`
      );
    });

    it("keeps the file header above the module wrapper", () => {
      const wrapped = addon.tsGenerateModuleWrapped("foo");
      assert.ok(
        wrapped.startsWith("// Auto-generated by Neon. Do not edit.\n"),
        `Expected header at top, got:\n${wrapped.slice(0, 100)}`
      );
    });
  });

  it("applies ts_returns override on methods", () => {
    assert.ok(
      declarations.includes("tsMethodReturns(): bigint"),
      `Expected tsMethodReturns to return bigint, got:\n${declarations}`
    );
  });

  it("applies per-param ts_type override", () => {
    assert.ok(
      declarations.includes("tsParamOverride(xs: ReadonlyArray<number>)"),
      `Expected ts_type override on param, got:\n${declarations}`
    );
  });

  it("applies ts_name to classes", () => {
    assert.ok(
      declarations.includes("declare class PublicName"),
      `Expected renamed class PublicName, got:\n${declarations}`
    );
    assert.ok(
      !/declare class Renamed\s/.test(declarations),
      `Expected original Rust name not in output, got:\n${declarations}`
    );
  });

  it("applies ts_name to methods", () => {
    assert.ok(
      declarations.includes("publicName(): string"),
      `Expected renamed method publicName, got:\n${declarations}`
    );
  });

  it('auto-attaches declarations under Symbol.for("neon:types")', () => {
    const fromSymbol = addon[Symbol.for("neon:types")];
    assert.strictEqual(typeof fromSymbol, "string");
    assert.ok(fromSymbol.length > 0);
  });

  it("emits export keyword on type aliases", () => {
    // Spot-check that collected declarations are exported.
    assert.ok(
      declarations.includes("export type SearchResult"),
      `Expected export keyword on SearchResult, got:\n${declarations}`
    );
    assert.ok(
      declarations.includes("export type Shape"),
      `Expected export keyword on Shape, got:\n${declarations}`
    );
  });
});
